---
- hosts: all
  tasks:

- name: install IIS features that are required
    win_dsc:
    resource_name: WindowsFeature
    Name: '{{item}}'
    Ensure: Present
  with_items:
  - Web-Server
  - Web-Asp-Net45
